import Navbar from "@/components/Navbar";
import type { Metadata } from "next";




export const metadata: Metadata = {
    title: "CMR",
    description: "Generated by create next app",
};

export default function AuthLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Navbar />
            {children}
        </>
    );
}
