import type { Metadata } from 'next'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import localFont from 'next/font/local'
import { Footer } from '@/components/Footer'

const clashDisplay = localFont({
    src: "../fonts/ClashDisplay-Variable.ttf",
    display: 'swap',
    variable: '--font-clash-display',
})

export const metadata: Metadata = {
    title: 'Clerk Next.js Quickstart',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={clashDisplay.className} >
                    {children}
                    <Footer />
                </body>
            </html>
        </ClerkProvider>
    )
}


